using H.Core.Enumerations;

namespace H.Core.Providers.Feed;

public interface IFeedIngredient
{
    string? IngredientTypeString { get; set; }
    IngredientType IngredientType { get; set; }
    double Sugars { get; set; }
    double SolubleCrudeProtein { get; set; }
    double DryMatter { get; set; }
    double CrudeProtein { get; set; }
    double CrudeFiber { get; set; }
    double AcidEtherExtract { get; set; }
    double GrossEnergy { get; set; }
    double Fat { get; set; }
    double TotalDigestibleNutrient { get; set; }
    double Starch { get; set; }
    string? IFN { get; set; }
    double Cost { get; set; }
    double Forage { get; set; }
    double RDP { get; set; }
    double ADF { get; set; }
    double ADL { get; set; }
    double Hemicellulose { get; set; }
    double TDF { get; set; }
    double IDF { get; set; }
    double SDF { get; set; }
    double Sucrose { get; set; }
    double Lactose { get; set; }
    double Glucose { get; set; }
    double Oligosaccharides { get; set; }
    double Raffinose { get; set; }
    double Stachyose { get; set; }
    double Verbascose { get; set; }
    double Mo { get; set; }

    /// <summary>
    /// used for cattle diets
    /// </summary>
    double DE { get; set; }

    /// <summary>
    /// used only for swine diets
    /// </summary>
    double DeSwine { get; set; }

    double SP { get; set; }
    double ADICP { get; set; }
    double OA { get; set; }
    double Ash { get; set; }
    double NDF { get; set; }
    double Lignin { get; set; }
    double Pef { get; set; }
    double ME { get; set; }
    double NEma { get; set; }
    double NEga { get; set; }
    double RUP { get; set; }
    double kdPB { get; set; }
    double KdCB1 { get; set; }
    double KdCB2 { get; set; }
    double KdCB3 { get; set; }
    double PBID { get; set; }
    double CB1ID { get; set; }
    double CB2ID { get; set; }
    double ARG { get; set; }
    double HIS { get; set; }
    double ILE { get; set; }
    double LEU { get; set; }
    double LYS { get; set; }
    double MET { get; set; }
    double CYS { get; set; }
    double PHE { get; set; }
    double TYR { get; set; }
    double THR { get; set; }
    double TRP { get; set; }
    double VAL { get; set; }
    double ALA { get; set; }
    double ASP { get; set; }
    double GLU { get; set; }
    double GLY { get; set; }
    double PRO { get; set; }
    double SER { get; set; }
    double CR { get; set; }
    double Ca { get; set; }
    double P { get; set; }
    double Mg { get; set; }
    double Cl { get; set; }
    double K { get; set; }
    double Na { get; set; }
    double S { get; set; }
    double Co { get; set; }
    double Cu { get; set; }
    double I { get; set; }
    double Fe { get; set; }
    double Mn { get; set; }
    double Se { get; set; }
    double Zn { get; set; }
    double VitA { get; set; }
    double VitD { get; set; }
    double VitE { get; set; }
    double VitD3 { get; set; }
    double vitB1 { get; set; }
    double VitB2 { get; set; }
    double VitB3 { get; set; }
    double VitB5 { get; set; }
    double VitB6 { get; set; }
    double VitB7 { get; set; }
    double VitB12 { get; set; }
    double PercentageInDiet { get; set; }
    string? FeedNumber { get; set; }
    DairyFeedClassType DairyFeedClass { get; set; }
    double PAF { get; set; }
    double NEL_ThreeX { get; set; }
    double NEL_FourX { get; set; }
    double NEM { get; set; }
    double NEG { get; set; }
    double NDICP { get; set; }
    double EE { get; set; }
    double Phytate { get; set; }
    double PhytatePhosphorus { get; set; }
    double NonPhytatePhosphorus { get; set; }
    double BetaCarotene { get; set; }
    double Choline { get; set; }
    double NE { get; set; }
    double CpDigestAID { get; set; }
    double ArgDigestAID { get; set; }
    double HisDigestAID { get; set; }
    double IleDigestAID { get; set; }
    double LeuDigestAID { get; set; }
    double LysDigestAID { get; set; }
    double MetDigestAID { get; set; }
    double PheDigestAID { get; set; }
    double ThrDigestAID { get; set; }
    double TrpDigestAID { get; set; }
    double ValDigestAID { get; set; }
    double AlaDigestAID { get; set; }
    double AspDigestAID { get; set; }
    double CysDigestAID { get; set; }
    double GluDigestAID { get; set; }
    double GlyDigestAID { get; set; }
    double ProDigestAID { get; set; }
    double SerDigestAID { get; set; }
    double TyrDigestAID { get; set; }
    double CpDigestSID { get; set; }
    double ArgDigestSID { get; set; }
    double HisDigestSID { get; set; }
    double IleDigestSID { get; set; }
    double LeuDigestSID { get; set; }
    double LysDigestSID { get; set; }
    double MetDigestSID { get; set; }
    double PheDigestSID { get; set; }
    double ThrDigestSID { get; set; }
    double TrpDigestSID { get; set; }
    double ValDigestSID { get; set; }
    double AlaDigestSID { get; set; }
    double AspDigestSID { get; set; }
    double CysDigestSID { get; set; }
    double GluDigestSID { get; set; }
    double GlyDigestSID { get; set; }
    double ProDigestSID { get; set; }
    double SerDigestSID { get; set; }
    double TyrDigestSID { get; set; }
    string? AAFCO { get; set; }
    string? AAFCO2010 { get; set; }
    double ATTDPhosphorus { get; set; }
    double STTDPhosphorus { get; set; }
    double Biotin { get; set; }
    double Folacin { get; set; }
    double Niacin { get; set; }
    double PantothenicAcid { get; set; }
    double Riboflavin { get; set; }
    double Thiamin { get; set; }
    double EtherExtractDup { get; set; }
    double C120 { get; set; }
    double C140 { get; set; }
    double C160 { get; set; }
    double C161 { get; set; }
    double C180 { get; set; }
    double C181 { get; set; }
    double C182 { get; set; }
    double C183 { get; set; }
    double C184 { get; set; }
    double C200 { get; set; }
    double C201 { get; set; }
    double C204 { get; set; }
    double C205 { get; set; }
    double C220 { get; set; }
    double C221 { get; set; }
    double C225 { get; set; }
    double C226 { get; set; }
    double C240 { get; set; }
    double SFA { get; set; }
    double MUFA { get; set; }
    double PUFA { get; set; }
    double IV { get; set; }
    double IVP { get; set; }
    double Nemf { get; }
    bool IsReadonly { get; set; }
}